// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaoY9JosI1DJAxFL4QM-At_wYIa-rCavw',
    appId: '1:413011049390:web:9aac256da193eb7f06e63f',
    messagingSenderId: '413011049390',
    projectId: 'campusmarket-9f6e0',
    authDomain: 'campusmarket-9f6e0.firebaseapp.com',
    storageBucket: 'campusmarket-9f6e0.firebasestorage.app',
    measurementId: 'G-XG1KBH2N99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hA6Lr9IMEg1fj5l5FWz8NFUjGSrdle0',
    appId: '1:413011049390:android:32a2a4d0cb76891106e63f',
    messagingSenderId: '413011049390',
    projectId: 'campusmarket-9f6e0',
    storageBucket: 'campusmarket-9f6e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuYueIHqA4dAMHNRJGLNhW5xOBI2XOHw',
    appId: '1:413011049390:ios:750249c33641e90306e63f',
    messagingSenderId: '413011049390',
    projectId: 'campusmarket-9f6e0',
    storageBucket: 'campusmarket-9f6e0.firebasestorage.app',
    iosBundleId: 'com.example.campusmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOuYueIHqA4dAMHNRJGLNhW5xOBI2XOHw',
    appId: '1:413011049390:ios:750249c33641e90306e63f',
    messagingSenderId: '413011049390',
    projectId: 'campusmarket-9f6e0',
    storageBucket: 'campusmarket-9f6e0.firebasestorage.app',
    iosBundleId: 'com.example.campusmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaoY9JosI1DJAxFL4QM-At_wYIa-rCavw',
    appId: '1:413011049390:web:8a0b89f8df29009d06e63f',
    messagingSenderId: '413011049390',
    projectId: 'campusmarket-9f6e0',
    authDomain: 'campusmarket-9f6e0.firebaseapp.com',
    storageBucket: 'campusmarket-9f6e0.firebasestorage.app',
    measurementId: 'G-KV4DT6149L',
  );
}
